allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: US_speednode_0030
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 278.1
  tls: false
  type: vless
  udp: true
  uuid: f8f19bc7-54c1-4612-9cff-4ce3852d2bba
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- flow: xtls-rprx-vision
  name: SG_speednode_0019
  port: 46920
  reality-opts:
    public-key: 26jcWQerQE3ryBAm1OCcC7MrgGlI5I-gpdel1xf2Hx8
  server: 43.160.246.221
  servername: aws.amazon.com
  skip-cert-verify: false
  speed: 254.2
  tls: true
  type: vless
  udp: true
  uuid: 33a0c07b-82c7-40c8-aac7-4ab2071bcc03
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 236.83
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: Êó•Êú¨3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 236.2
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 226.17
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 193.96
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- cipher: chacha20-ietf-poly1305
  name: üáØüáµ Êó•Êú¨4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 172.105.217.136
  speed: 189.01
  type: ss
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 187.18
  tls: false
  type: hysteria2
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 167.92
  tls: false
  type: hysteria2
- cipher: chacha20-ietf-poly1305
  name: üáπüáº Âè∞Êπæ|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 60.249.35.3
  speed: 163.17
  type: ss
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 159.25
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 154.02
  type: trojan
- name: DE_speednode_0004
  port: 29973
  reality-opts:
    public-key: QqNYhBZPJmHBGFF_4WsxNPcH8xve-4gma9--drcflHQ
    short-id: cd6229f31e7180e6
  server: 185.161.251.24
  servername: yandex.ru
  skip-cert-verify: false
  speed: 111.98
  tls: true
  type: vless
  udp: true
  uuid: a1493ccd-d1a4-4087-9041-1b3500224003
- flow: xtls-rprx-vision
  name: US_speednode_0028
  port: 443
  reality-opts:
    public-key: VA5-XSH73WyopK0i8jc2i-23N0VPVwmN8w7TX1MnVyg
    short-id: 9df18b8856e52959
  server: 185.177.238.80
  servername: nl3.truservice.top
  skip-cert-verify: false
  speed: 110.22
  tls: true
  type: vless
  udp: true
  uuid: 1762a070-294a-4999-9c59-05aa4922feed
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - US_speednode_0030
  - SG_speednode_0019
  - RU_speednode_0017
  - Êó•Êú¨3|@ripaojiedian
  - RU_speednode_0015
  - RU_speednode_0016
  - üáØüáµ Êó•Êú¨4|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - '@V2rayNG3'
  - üáπüáº Âè∞Êπæ|@ripaojiedian
  - US_speednode_0023
  - ÁæéÂõΩ3|@ripaojiedian
  - DE_speednode_0004
  - US_speednode_0028
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
