allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: RU_speednode_0044
  network: ws
  password: 14d6efcf-b0d3-4054-9d4e-e1347e3ceaa2
  port: 2053
  server: 213.159.208.88
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 286.31
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/213.159.208.88=2053
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 277.38
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 246.93
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 234.32
  tls: false
  type: hysteria2
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 231.63
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 210.55
  tls: false
  type: hysteria2
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.51.29
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 206.19
  type: trojan
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 206.1
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 112.120.34.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 201.81
  type: trojan
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 194.09
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 187.8
  type: trojan
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 185.26
  tls: false
  type: hysteria2
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 153.13
  type: trojan
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 151.44
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 20579
  reality-opts:
    public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
    short-id: 89f1da93
  server: 152.53.84.101
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 144.87
  tls: true
  type: vless
  udp: true
  uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.183.80
  speed: 141.41
  type: ss
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 38.180.191.251
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 127.85
  type: trojan
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 124.93
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 119.08
  type: trojan
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 118.51
  type: trojan
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 113.17
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 172.105.217.136
  speed: 113.02
  type: ss
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 112.74
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- flow: xtls-rprx-vision
  name: IL_speednode_0020
  port: 443
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  servername: i2pd.website
  skip-cert-verify: false
  speed: 111.41
  tls: true
  type: vless
  udp: true
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 110.66
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- flow: xtls-rprx-vision
  name: RU_speednode_0041
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 109.38
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 106.44
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - RU_speednode_0044
  - SI_speednode_0048
  - US_speednode_0050
  - '@NoForcedheaven'
  - é¦™æ¸¯3|@ripaojiedian
  - '@V2rayNG3'
  - æ–°åŠ å¡2|@ripaojiedian
  - IQ_speednode_0030
  - é¦™æ¸¯5|@ripaojiedian
  - NL_speednode_0037
  - ç¾å›½3|@ripaojiedian
  - MCI-IR--@V2rayAlpha-7
  - æ—¥æœ¬3|@ripaojiedian
  - SE_speednode_0046
  - AT_speednode_0003
  - ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - SI_speednode_0047
  - æ–°åŠ å¡|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - PL_speednode_0039
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - BG_speednode_0006
  - IL_speednode_0020
  - IT_speednode_0031
  - RU_speednode_0041
  - ç¾å›½2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
