allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 286.06
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 273.46
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 272.13
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.57.238
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 258.69
  type: trojan
- name: US_speednode_0030
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 230.35
  tls: false
  type: vless
  udp: true
  uuid: f8f19bc7-54c1-4612-9cff-4ce3852d2bba
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- flow: xtls-rprx-vision
  name: US_speednode_0026
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 226.25
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: US_speednode_0028
  port: 443
  reality-opts:
    public-key: VA5-XSH73WyopK0i8jc2i-23N0VPVwmN8w7TX1MnVyg
    short-id: 9df18b8856e52959
  server: 185.177.238.80
  servername: nl3.truservice.top
  skip-cert-verify: false
  speed: 222.08
  tls: true
  type: vless
  udp: true
  uuid: 1762a070-294a-4999-9c59-05aa4922feed
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 204.48
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 188.88
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 174.58
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 139.94
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- cipher: chacha20-ietf
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.183.80
  speed: 132.33
  type: ss
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.51.29
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 122.4
  type: trojan
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 116.29
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 60.249.35.3
  speed: 114.27
  type: ss
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 113.28
  type: trojan
- client-fingerprint: firefox
  name: DE_speednode_0002
  port: 9107
  reality-opts:
    public-key: Go_wk-NFoenM3xuCSQ84_0Lzh3Y6XrHzTz8XTbQl8lI
    short-id: e8ef8df79e4a6343
  server: 195.254.165.152
  servername: refersion.com
  skip-cert-verify: false
  speed: 104.51
  tls: true
  type: vless
  udp: true
  uuid: 774727ed-1e56-41bd-b55f-28549e21bcc8
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - æ–°åŠ å¡|@ripaojiedian
  - RU_speednode_0017
  - RU_speednode_0016
  - æ—¥æœ¬2|@ripaojiedian
  - US_speednode_0030
  - US_speednode_0026
  - US_speednode_0028
  - US_speednode_0023
  - ç¾å›½3|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - RU_speednode_0015
  - ğŸ‡­ğŸ‡° é¦™æ¸¯6|@ripaojiedian
  - æ–°åŠ å¡2|@ripaojiedian
  - æ—¥æœ¬3|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - æ—¥æœ¬|@ripaojiedian
  - DE_speednode_0002
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
