allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: È¶ôÊ∏Ø4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 203.198.122.97
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 295.28
  type: trojan
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 292.22
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: Êó•Êú¨3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.196.59
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 285.99
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0041
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 285.88
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 278.73
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 276.45
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 264.14
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 250.76
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- name: DK_speednode_0011
  network: ws
  password: 63b8ce6d-9a30-4122-a00f-fd47f020dc27
  port: 443
  server: 89.28.236.243
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 243.72
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
- name: È¶ôÊ∏Ø5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.77.239.35
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 231.95
  type: trojan
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 229.71
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 37876
  reality-opts:
    public-key: ldoGIafEPJu2W4gODAoLjobXOOe9NKb-110WCz1-EwM
    short-id: 907e
  server: 152.53.133.12
  servername: yelp.com
  skip-cert-verify: false
  speed: 227.73
  tls: true
  type: vless
  udp: true
  uuid: 29397c5b-be3b-41d9-8a49-21575668e915
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 205.1
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 203.51
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: LU_speednode_0033
  port: 17715
  reality-opts:
    public-key: itR04_u2Xo8xZ4a9Kk2U-pul4hNXzZYskdHdx4rjO0s
    short-id: 0db891a2
  server: ezalor.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 184.02
  tls: true
  type: vless
  udp: true
  uuid: 9627bc06-1a36-4674-aeb8-4e863b8bd979
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 172.45
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: JP_speednode_0032
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: usa.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 165.1
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: AT_speednode_0005
  port: 22925
  reality-opts:
    public-key: Pzsb-3zlxbYLJwRE0ACSqzTL7h3ubqREGMEs17q_1z4
    short-id: 886d
  server: 152.53.147.69
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 161.84
  tls: true
  type: vless
  udp: true
  uuid: 0226ef52-e556-4f36-ab0f-6c9f5414942a
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4094
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 159.46
  type: trojan
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: AT_speednode_0001
  port: 10668
  reality-opts:
    public-key: Q6xd8H-9jQy5bqqAaCqHqV1VKkzbp2-tzwQGjgoI8GI
    short-id: f7
  server: sandking.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 153.93
  tls: true
  type: vless
  udp: true
  uuid: 53e91da4-f382-4b8e-890a-2499bc877554
- name: Êñ∞Âä†Âù°|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2760
  server: 160.16.81.84
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 140.56
  type: trojan
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 132.43
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 129.92
  tls: false
  type: hysteria2
- name: PL_speednode_0038
  network: ws
  password: 55d19115-ec40-407b-a674-74e6a948347a
  port: 2053
  server: 45.144.48.55
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 120.67
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.55=2053
- flow: xtls-rprx-vision
  name: FR_speednode_0014
  port: 33009
  reality-opts:
    public-key: vQxUlk2tCENv9crfrUAp5JdJOZTKhMH7XnoKLqbAYx0
    short-id: c0d304da0c4dcadc
  server: 195.154.42.111
  servername: www.yahoo.com
  skip-cert-verify: false
  speed: 119.51
  tls: true
  type: vless
  udp: true
  uuid: 77a33d77-7af9-4c33-9556-d6711becca04
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 20579
  reality-opts:
    public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
    short-id: 89f1da93
  server: 152.53.84.101
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 114.96
  tls: true
  type: vless
  udp: true
  uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
- name: RU_speednode_0042
  port: 58871
  reality-opts:
    public-key: J4NvMlw9Hue3ELYmxP4HQXJ71tf2BAIhOLSyIRkNekA
    short-id: 05aa79ca512b2a58
  server: 81.177.214.214
  servername: yandex.ru
  skip-cert-verify: false
  speed: 108.7
  tls: true
  type: vless
  udp: true
  uuid: 74973884-76d6-4e51-a20f-c15b0acaf1d3
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 105.41
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- flow: xtls-rprx-vision
  name: IQ_speednode_0025
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: frs.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 104.04
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- cipher: chacha20-ietf
  name: üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.182.158
  speed: 103.86
  type: ss
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - È¶ôÊ∏Ø4|@ripaojiedian
  - SI_speednode_0048
  - Êó•Êú¨3|@ripaojiedian
  - RU_speednode_0041
  - NL_speednode_0037
  - IT_speednode_0031
  - US_speednode_0050
  - BG_speednode_0006
  - DK_speednode_0011
  - È¶ôÊ∏Ø5|@ripaojiedian
  - PL_speednode_0039
  - AT_speednode_0002
  - MCI-IR--@V2rayAlpha-14
  - RU_speednode_0043
  - LU_speednode_0033
  - IQ_speednode_0030
  - JP_speednode_0032
  - AT_speednode_0005
  - ÁæéÂõΩ3|@ripaojiedian
  - AT_speednode_0001
  - Êñ∞Âä†Âù°|@ripaojiedian
  - MCI-IR--@V2rayAlpha-7
  - '@NoForcedheaven'
  - PL_speednode_0038
  - FR_speednode_0014
  - AT_speednode_0003
  - RU_speednode_0042
  - IL_speednode_0021
  - IQ_speednode_0025
  - üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
