allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 256.34
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- name: æ–°åŠ å¡2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 153.121.51.29
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 245.23
  type: trojan
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5552
  server: 160.16.236.32
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 233.27
  type: trojan
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 38.180.191.251
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 225.75
  type: trojan
- name: ç¾å›½2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 4211
  server: 160.16.57.238
  skip-cert-verify: true
  sni: www.nintendogames.net
  speed: 205.12
  type: trojan
- name: ç¾å›½3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4569
  server: us.wyau.cn
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 186.17
  type: trojan
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 174.05
  tls: false
  type: hysteria2
- name: DE_speednode_0004
  port: 29973
  reality-opts:
    public-key: QqNYhBZPJmHBGFF_4WsxNPcH8xve-4gma9--drcflHQ
    short-id: cd6229f31e7180e6
  server: 185.161.251.24
  servername: yandex.ru
  skip-cert-verify: false
  speed: 172.15
  tls: true
  type: vless
  udp: true
  uuid: a1493ccd-d1a4-4087-9041-1b3500224003
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 171.31
  tls: false
  type: hysteria2
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 169.5
  tls: false
  type: hysteria2
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 172.105.217.136
  speed: 125.69
  type: ss
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 124.88
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: US_speednode_0030
  network: ws
  port: 80
  server: www.speedtest.net
  servername: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
  skip-cert-verify: false
  speed: 124.77
  tls: false
  type: vless
  udp: true
  uuid: f8f19bc7-54c1-4612-9cff-4ce3852d2bba
  ws-opts:
    headers:
      Host: websocket.network.www.speedtest.net.flutter.dev.russia.pyt.digitalcity5.xyz.
    path: /@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy----@Shh_Proxy
- name: æ—¥æœ¬|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 1924
  server: 160.16.227.93
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 122.52
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: e221b75:110505
    mode: tls
  port: 2377
  server: 60.249.35.3
  speed: 122.18
  type: ss
- name: All-@V2rayAlpha--44
  password: 862e90e1-2f26-4506-b8b9-0adf20da05fc
  port: 47262
  server: 40.233.103.51
  skip-cert-verify: true
  sni: www.bing.com
  speed: 117.84
  tls: false
  type: hysteria2
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.57.238
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 114.41
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 106.79
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 202.181.103.235
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 100.69
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - RU_speednode_0016
  - æ–°åŠ å¡2|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - æ–°åŠ å¡3|@ripaojiedian
  - ç¾å›½2|@ripaojiedian
  - ç¾å›½3|@ripaojiedian
  - '@V2rayNG3'
  - DE_speednode_0004
  - MCI-IR--@V2rayAlpha-14
  - MCI-IR--@V2rayAlpha-7
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - US_speednode_0023
  - US_speednode_0030
  - æ—¥æœ¬|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - All-@V2rayAlpha--44
  - æ—¥æœ¬2|@ripaojiedian
  - RU_speednode_0015
  - æ—¥æœ¬3|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
