allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- cipher: chacha20-ietf
  name: üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.182.158
  speed: 281.5
  type: ss
- name: NL_speednode_0036
  network: ws
  password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
  port: 443
  server: 86.107.197.239
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 281.28
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
- flow: xtls-rprx-vision
  name: JP_speednode_0032
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: usa.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 279.52
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 278.81
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 249.65
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: IQ_speednode_0028
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: sws.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 236.21
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 233.8
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 221.2
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: DK_speednode_0011
  network: ws
  password: 63b8ce6d-9a30-4122-a00f-fd47f020dc27
  port: 443
  server: 89.28.236.243
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 209.9
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 208.4
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: AT_speednode_0003
  port: 20579
  reality-opts:
    public-key: mT6lh-gtbEuWk3Zk6XGF_hYvpLwxTyvwtH7F-_fRbxI
    short-id: 89f1da93
  server: 152.53.84.101
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 188.74
  tls: true
  type: vless
  udp: true
  uuid: 93cd7e0f-8a81-4076-be8b-6d3bf3f8f810
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 179.76
  tls: false
  type: hysteria2
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 160.1
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: PL_speednode_0038
  network: ws
  password: 55d19115-ec40-407b-a674-74e6a948347a
  port: 2053
  server: 45.144.48.55
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 157.68
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.55=2053
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 156.87
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 54663
  reality-opts:
    public-key: HqZHmZub8Q43m2n10fkdH133wVdYgnLEnIUGpypaQno
    short-id: 2eb3cddded
  server: 152.53.143.63
  servername: stackoverflow.com
  skip-cert-verify: false
  speed: 151.17
  tls: true
  type: vless
  udp: true
  uuid: c088d5a0-cdc3-4880-8bd7-44ecef474ba2
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 131.72
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 127.12
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 124.41
  tls: false
  type: hysteria2
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4094
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 114.06
  type: trojan
- flow: xtls-rprx-vision
  name: FR_speednode_0014
  port: 33009
  reality-opts:
    public-key: vQxUlk2tCENv9crfrUAp5JdJOZTKhMH7XnoKLqbAYx0
    short-id: c0d304da0c4dcadc
  server: 195.154.42.111
  servername: www.yahoo.com
  skip-cert-verify: false
  speed: 106.51
  tls: true
  type: vless
  udp: true
  uuid: 77a33d77-7af9-4c33-9556-d6711becca04
- name: Êñ∞Âä†Âù°2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5553
  server: 160.16.124.55
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 100.63
  type: trojan
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  - NL_speednode_0036
  - JP_speednode_0032
  - IL_speednode_0021
  - SI_speednode_0048
  - IQ_speednode_0028
  - US_speednode_0050
  - IQ_speednode_0030
  - DK_speednode_0011
  - MCI-IR--@V2rayAlpha-14
  - AT_speednode_0003
  - MCI-IR--@V2rayAlpha-7
  - SI_speednode_0047
  - PL_speednode_0038
  - NL_speednode_0037
  - AT_speednode_0004
  - IT_speednode_0031
  - '@V2rayNG3'
  - '@NoForcedheaven'
  - ÁæéÂõΩ3|@ripaojiedian
  - FR_speednode_0014
  - Êñ∞Âä†Âù°2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
