allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 296.2
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: IL_speednode_0020
  port: 443
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  servername: i2pd.website
  skip-cert-verify: false
  speed: 287.75
  tls: true
  type: vless
  udp: true
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
- flow: xtls-rprx-vision
  name: IQ_speednode_0025
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: frs.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 284.22
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 272.38
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 265.72
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 247.55
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 245.92
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.77.239.35
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 211.03
  type: trojan
- name: NL_speednode_0036
  network: ws
  password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
  port: 443
  server: 86.107.197.239
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 194.29
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 184.52
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- flow: xtls-rprx-vision
  name: AT_speednode_0004
  port: 54663
  reality-opts:
    public-key: HqZHmZub8Q43m2n10fkdH133wVdYgnLEnIUGpypaQno
    short-id: 2eb3cddded
  server: 152.53.143.63
  servername: stackoverflow.com
  skip-cert-verify: false
  speed: 180.93
  tls: true
  type: vless
  udp: true
  uuid: c088d5a0-cdc3-4880-8bd7-44ecef474ba2
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 180.28
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
- flow: xtls-rprx-vision
  name: FR_speednode_0014
  port: 33009
  reality-opts:
    public-key: vQxUlk2tCENv9crfrUAp5JdJOZTKhMH7XnoKLqbAYx0
    short-id: c0d304da0c4dcadc
  server: 195.154.42.111
  servername: www.yahoo.com
  skip-cert-verify: false
  speed: 170.88
  tls: true
  type: vless
  udp: true
  uuid: 77a33d77-7af9-4c33-9556-d6711becca04
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 162.99
  tls: false
  type: hysteria2
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 154.55
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 142.88
  tls: false
  type: hysteria2
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 120.56
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: RU_speednode_0041
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 119.49
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 203.198.122.97
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 109.28
  type: trojan
proxy-groups:
- name: 自动选择
  proxies:
  - '@V2rayNG3'
  - IL_speednode_0020
  - IQ_speednode_0025
  - SE_speednode_0046
  - IL_speednode_0021
  - RU_speednode_0043
  - US_speednode_0050
  - 香港5|@ripaojiedian
  - NL_speednode_0036
  - BG_speednode_0006
  - AT_speednode_0004
  - PL_speednode_0039
  - FR_speednode_0014
  - MCI-IR--@V2rayAlpha-7
  - SI_speednode_0047
  - MCI-IR--@V2rayAlpha-14
  - SI_speednode_0048
  - RU_speednode_0041
  - 香港4|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
