allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: IQ_speednode_0028
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: sws.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 271.57
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: MCI-IR--@V2rayAlpha-7
  password: 9ec830fd-79da-4706-a964-cb227d7198db
  port: 33333
  server: 135.148.82.248
  skip-cert-verify: true
  speed: 231.14
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 230.99
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 206.08
  tls: false
  type: hysteria2
- name: DK_speednode_0011
  network: ws
  password: 63b8ce6d-9a30-4122-a00f-fd47f020dc27
  port: 443
  server: 89.28.236.243
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 190.94
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 189.39
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: Êñ∞Âä†Âù°|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 2760
  server: 160.16.81.84
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 183.09
  type: trojan
- cipher: chacha20-ietf
  name: üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  password: asd123456
  port: 8388
  server: 103.149.182.158
  speed: 158.43
  type: ss
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 151.04
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 150.76
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: IL_speednode_0020
  port: 443
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  servername: i2pd.website
  skip-cert-verify: false
  speed: 146.27
  tls: true
  type: vless
  udp: true
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 138.31
  tls: false
  type: hysteria2
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 123.97
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: US_speednode_0050
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: autos.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 122.05
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 121.08
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
- name: RU_speednode_0044
  network: ws
  password: 14d6efcf-b0d3-4054-9d4e-e1347e3ceaa2
  port: 2053
  server: 213.159.208.88
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 119.66
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/213.159.208.88=2053
- name: Êó•Êú¨2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 1334
  server: 160.16.132.158
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 118.1
  type: trojan
- flow: xtls-rprx-vision
  name: US_speednode_0055
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 116.54
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: RU_speednode_0041
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 116.06
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: ÁæéÂõΩ3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 4094
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 113.05
  type: trojan
- name: PL_speednode_0038
  network: ws
  password: 55d19115-ec40-407b-a674-74e6a948347a
  port: 2053
  server: 45.144.48.55
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 108.98
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.55=2053
- name: È¶ôÊ∏Ø5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.77.239.35
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 108.0
  type: trojan
- name: Êñ∞Âä†Âù°2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 5553
  server: 160.16.124.55
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 102.54
  type: trojan
proxy-groups:
- name: Ëá™Âä®ÈÄâÊã©
  proxies:
  - IQ_speednode_0028
  - MCI-IR--@V2rayAlpha-7
  - RU_speednode_0043
  - MCI-IR--@V2rayAlpha-14
  - DK_speednode_0011
  - SI_speednode_0047
  - Êñ∞Âä†Âù°|@ripaojiedian
  - üá≠üá∞ È¶ôÊ∏Ø6|@ripaojiedian
  - SI_speednode_0048
  - '@V2rayNG3'
  - IL_speednode_0020
  - '@NoForcedheaven'
  - IQ_speednode_0030
  - US_speednode_0050
  - SE_speednode_0046
  - RU_speednode_0044
  - Êó•Êú¨2|@ripaojiedian
  - US_speednode_0055
  - RU_speednode_0041
  - ÁæéÂõΩ3|@ripaojiedian
  - PL_speednode_0038
  - È¶ôÊ∏Ø5|@ripaojiedian
  - Êñ∞Âä†Âù°2|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Ëá™Âä®ÈÄâÊã©
socks-port: 7891
