allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- flow: xtls-rprx-vision
  name: RU_speednode_0017
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: 5.129.252.60
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 276.08
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: é¦™æ¸¯3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 443
  server: 58.152.110.216
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 261.84
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 59.125.62.188
  speed: 246.13
  type: ss
- name: æ–°åŠ å¡|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 127
  server: 160.16.151.196
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 229.16
  type: trojan
- name: é¦™æ¸¯4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 58.152.26.173
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 194.3
  type: trojan
- flow: xtls-rprx-vision
  name: US_speednode_0023
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: fis.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 191.65
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: '@V2rayNG3'
  password: '123456'
  port: 443
  server: 192.3.85.237
  skip-cert-verify: true
  sni: bing.com
  speed: 184.38
  tls: false
  type: hysteria2
- name: æ–°åŠ å¡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 3579
  server: 116.49.237.130
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 170.06
  type: trojan
- name: MCI-IR--@V2rayAlpha-14
  password: 2b195c17-5ff5-4b0d-a809-210b92212394
  port: 443
  server: falankefu1.nezhasu.com
  skip-cert-verify: true
  sni: falankefu1.nezhasu.com
  speed: 155.38
  tls: false
  type: hysteria2
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 151.99
  tls: false
  type: hysteria2
- name: é¦™æ¸¯5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.79.165.55
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 139.96
  type: trojan
- client-fingerprint: firefox
  name: DE_speednode_0002
  port: 9107
  reality-opts:
    public-key: Go_wk-NFoenM3xuCSQ84_0Lzh3Y6XrHzTz8XTbQl8lI
    short-id: e8ef8df79e4a6343
  server: 195.254.165.152
  servername: refersion.com
  skip-cert-verify: false
  speed: 137.24
  tls: true
  type: vless
  udp: true
  uuid: 774727ed-1e56-41bd-b55f-28549e21bcc8
- cipher: chacha20-ietf-poly1305
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)9d3f6ec:160648
    mode: tls
  port: 2377
  server: 3.112.229.1
  speed: 133.64
  type: ss
- name: RU_speednode_0016
  network: ws
  password: -4146XJHYAzJ4K8Ov6_LBQ
  port: 11000
  server: 194.35.116.62
  skip-cert-verify: false
  sni: f4e23c6c168f0e91.noproblemvpn.ru
  speed: 111.28
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: f4e23c6c168f0e91.noproblemvpn.ru
    path: /tw
- name: æ—¥æœ¬2|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 153.121.65.107
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 106.36
  type: trojan
- flow: xtls-rprx-vision
  name: RU_speednode_0015
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 103.19
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- name: æ—¥æœ¬3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.63.16
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 102.5
  type: trojan
proxy-groups:
- name: è‡ªåŠ¨é€‰æ‹©
  proxies:
  - RU_speednode_0017
  - é¦™æ¸¯3|@ripaojiedian
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾|@ripaojiedian
  - æ–°åŠ å¡|@ripaojiedian
  - é¦™æ¸¯4|@ripaojiedian
  - US_speednode_0023
  - '@V2rayNG3'
  - æ–°åŠ å¡3|@ripaojiedian
  - MCI-IR--@V2rayAlpha-14
  - '@NoForcedheaven'
  - é¦™æ¸¯5|@ripaojiedian
  - DE_speednode_0002
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬4|@ripaojiedian
  - RU_speednode_0016
  - æ—¥æœ¬2|@ripaojiedian
  - RU_speednode_0015
  - æ—¥æœ¬3|@ripaojiedian
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,è‡ªåŠ¨é€‰æ‹©
socks-port: 7891
