allow-lan: false
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies:
- name: NL_speednode_0036
  network: ws
  password: 5ad5fe82-6b60-4f59-977b-93910ef7a9ca
  port: 443
  server: 86.107.197.239
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 297.29
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
- name: 香港5|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 443
  server: 219.77.239.35
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  speed: 292.06
  type: trojan
- name: IT_speednode_0031
  network: ws
  password: d5a49621-b25c-4684-aea8-8389f3a8afaf
  port: 8443
  server: 94.177.199.119
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 291.54
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
- flow: xtls-rprx-vision
  name: IQ_speednode_0030
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: ges.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 291.17
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: FR_speednode_0014
  port: 33009
  reality-opts:
    public-key: vQxUlk2tCENv9crfrUAp5JdJOZTKhMH7XnoKLqbAYx0
    short-id: c0d304da0c4dcadc
  server: 195.154.42.111
  servername: www.yahoo.com
  skip-cert-verify: false
  speed: 287.02
  tls: true
  type: vless
  udp: true
  uuid: 77a33d77-7af9-4c33-9556-d6711becca04
- flow: xtls-rprx-vision
  name: IQ_speednode_0025
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: 4c02bbbfa833b3b6
  server: frs.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 285.93
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- flow: xtls-rprx-vision
  name: AT_speednode_0002
  port: 37876
  reality-opts:
    public-key: ldoGIafEPJu2W4gODAoLjobXOOe9NKb-110WCz1-EwM
    short-id: 907e
  server: 152.53.133.12
  servername: yelp.com
  skip-cert-verify: false
  speed: 281.34
  tls: true
  type: vless
  udp: true
  uuid: 29397c5b-be3b-41d9-8a49-21575668e915
- flow: xtls-rprx-vision
  name: RU_speednode_0043
  port: 4442
  reality-opts:
    public-key: HCkRC28M16WYrORNt2-Bga_3AuxuGnphlAwXHY9R4SI
    short-id: fd99
  server: 193.124.182.224
  servername: dl.google.com
  skip-cert-verify: false
  speed: 275.78
  tls: true
  type: vless
  udp: true
  uuid: 9429f5ce-ed0f-48e7-afda-12f7b23441af
- flow: xtls-rprx-vision
  name: BG_speednode_0006
  port: 443
  reality-opts:
    public-key: ZmcE7f2ZycnrnsUSPkCrPBIGYC8dM4b27DX47DwCHXk
    short-id: 473915f2ef487f
  server: albania.solobot.ru
  servername: yahoo.com
  skip-cert-verify: false
  speed: 274.83
  tls: true
  type: vless
  udp: true
  uuid: 678bbdc1-7307-4cf2-bec1-bcdbd8efdbe5
- flow: xtls-rprx-vision
  name: RU_speednode_0041
  port: 443
  reality-opts:
    public-key: MNTWCLyV7EquFn-J0a6KRlQZ0dt6QY5mmu7Dq8uDkxw
    short-id: c2a0b2d60a7fc300
  server: youtube.jykvpn.com
  servername: cdnjs.com
  skip-cert-verify: false
  speed: 267.65
  tls: true
  type: vless
  udp: true
  uuid: 56718b04-3fe6-4ef3-a61f-cd9b3b5f64f1
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: LU_speednode_0034
  port: 29300
  reality-opts:
    public-key: kJzMBU-gwtqNcJx_igad-d891SBXixmCh78WTIRTIQk
    short-id: 5a
  server: amsterdam.fonixapp.org
  servername: canva.com
  skip-cert-verify: false
  speed: 260.14
  tls: true
  type: vless
  udp: true
  uuid: 7843d0a1-be6f-4b7f-92e2-8040711b434c
- name: DK_speednode_0011
  network: ws
  password: 63b8ce6d-9a30-4122-a00f-fd47f020dc27
  port: 443
  server: 89.28.236.243
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 253.73
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
- name: RU_speednode_0044
  network: ws
  password: 14d6efcf-b0d3-4054-9d4e-e1347e3ceaa2
  port: 2053
  server: 213.159.208.88
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 247.26
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/213.159.208.88=2053
- name: '@NoForcedheaven'
  obfs: salamander
  obfs-password: 9242a8bf
  password: a2678c97b8d79059
  port: 443
  server: 46.62.152.236
  skip-cert-verify: true
  speed: 231.88
  tls: false
  type: hysteria2
- name: PL_speednode_0039
  network: ws
  password: 49d416e1-4cec-41e1-bff6-3748c466f275
  port: 8443
  server: 45.144.48.158
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 231.86
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/45.144.48.158=8443
- name: SI_speednode_0048
  network: ws
  port: 443
  server: 45.144.52.23
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 209.91
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- name: IL_speednode_0021
  network: ws
  password: de763850-1022-4a03-a1ac-84422cfcd4fb
  port: 2053
  server: 77.91.69.238
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 204.19
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.91.69.238=2053
- client-fingerprint: firefox
  flow: xtls-rprx-vision
  name: LU_speednode_0033
  port: 17715
  reality-opts:
    public-key: itR04_u2Xo8xZ4a9Kk2U-pul4hNXzZYskdHdx4rjO0s
    short-id: 0db891a2
  server: ezalor.fonixapp.org
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 183.8
  tls: true
  type: vless
  udp: true
  uuid: 9627bc06-1a36-4674-aeb8-4e863b8bd979
- name: NL_speednode_0037
  network: ws
  password: f5eaa93a-4660-46a8-a1fd-bf993c7da57c
  port: 8443
  server: 185.121.233.231
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 183.16
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/185.121.233.231=8443
- flow: xtls-rprx-vision
  name: AT_speednode_0005
  port: 22925
  reality-opts:
    public-key: Pzsb-3zlxbYLJwRE0ACSqzTL7h3ubqREGMEs17q_1z4
    short-id: 886d
  server: 152.53.147.69
  servername: ilovepdf.com
  skip-cert-verify: false
  speed: 177.4
  tls: true
  type: vless
  udp: true
  uuid: 0226ef52-e556-4f36-ab0f-6c9f5414942a
- name: SI_speednode_0047
  network: ws
  port: 443
  server: fl-3-direct.djarbnet.ru
  servername: fl-3-direct.djarbnet.ru
  skip-cert-verify: false
  speed: 159.57
  tls: true
  type: vless
  udp: true
  uuid: cc67ca7f-064e-4117-ac31-a66d5728a11c
  ws-opts:
    headers:
      Host: fl-3-direct.djarbnet.ru
    path: /getupdates
- flow: xtls-rprx-vision
  name: IL_speednode_0020
  port: 443
  reality-opts:
    public-key: YVDo7U4O-AT2fa5H9E7hyYHKgfZd1vB6UdbAf2ggWQE
    short-id: 55e6af1a35e64a98
  server: ilta-wzxrxkdhbjpnprhkkpplsjwawhssvollvxzdhqshiqckwdgrdm.orbnet.xyz
  servername: i2pd.website
  skip-cert-verify: false
  speed: 145.42
  tls: true
  type: vless
  udp: true
  uuid: 0e8a6896-ad90-4a3b-89a3-77d64aa409e2
- name: 日本3|@ripaojiedian
  network: tcp
  password: 2274c52572e721086f8bd8f88984643c
  port: 3169
  server: 160.16.196.59
  skip-cert-verify: false
  sni: www.nintendogames.net
  speed: 123.06
  type: trojan
- name: SE_speednode_0046
  network: ws
  password: edeff73d-065d-4b0a-b848-aad9d3380223
  port: 443
  server: 77.221.141.207
  skip-cert-verify: false
  sni: joss.dus.biz.id
  speed: 100.05
  type: trojan
  udp: true
  ws-opts:
    headers:
      Host: joss.dus.biz.id
    path: /Free-VPN-CF-Geo-Project/77.221.141.207=443
proxy-groups:
- name: 自动选择
  proxies:
  - NL_speednode_0036
  - 香港5|@ripaojiedian
  - IT_speednode_0031
  - IQ_speednode_0030
  - FR_speednode_0014
  - IQ_speednode_0025
  - AT_speednode_0002
  - RU_speednode_0043
  - BG_speednode_0006
  - RU_speednode_0041
  - LU_speednode_0034
  - DK_speednode_0011
  - RU_speednode_0044
  - '@NoForcedheaven'
  - PL_speednode_0039
  - SI_speednode_0048
  - IL_speednode_0021
  - LU_speednode_0033
  - NL_speednode_0037
  - AT_speednode_0005
  - SI_speednode_0047
  - IL_speednode_0020
  - 日本3|@ripaojiedian
  - SE_speednode_0046
  type: select
rules:
- DOMAIN-SUFFIX,local,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,自动选择
socks-port: 7891
